Raise a better error when weights are 0 and not using a masked array
This is to raise a better error than the Numpy one which is not so
clear:

    ValueError: On entry to DLASCL parameter number 4 had an illegal value